In [1]:
#Q 1
# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [3]:
def dvd_by_zero_chk():
    while True:
        try:
            y = int(input("Please enter a number: "))
            x = 5 / y
        except ZeroDivisionError as e:
            print("\tError -- {}".format(e))
            print("\t\t5 is not divisible by zero.\n\t\tPlease enter correct value which is greater than zero.")
        except:
            print("\tOther error")
        else:
            print("\t5 is divisible by {}".format(y))
            print("\t\tGood work!")
            break

In [6]:
dvd_by_zero_chk()

Please enter a number:  0


	Error -- division by zero
		5 is not divisible by zero.
		Please enter correct value which is greater than zero.


Please enter a number:  1


	5 is divisible by 1
		Good work!


In [ ]:
#Q 2
# Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [7]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
out = ''
for sub in subjects[:]:
    for verb in verbs[:]:
        for object in objects[:]:
            out = out + '\n' + sub + ' ' + verb + ' ' + object +'.'
print(out)


Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [ ]:
# Q 3
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

In [8]:
import numpy as np
x = np.array([1,4,3,7])  # input array
N = 3 #Number of columns in the output. If N is not specified, a square array is returned
x

array([1, 4, 3, 7])

In [9]:
np.vander(x)

array([[  1,   1,   1,   1],
       [ 64,  16,   4,   1],
       [ 27,   9,   3,   1],
       [343,  49,   7,   1]])

In [10]:
np.vander(x,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   4,  16,  64],
       [  1,   3,   9,  27],
       [  1,   7,  49, 343]])

In [28]:
np.vander(x,increasing=False)

array([[  1,   1,   1,   1],
       [ 64,  16,   4,   1],
       [ 27,   9,   3,   1],
       [343,  49,   7,   1]])

In [11]:
np.vander(x,N)

array([[ 1,  1,  1],
       [16,  4,  1],
       [ 9,  3,  1],
       [49,  7,  1]])

In [12]:
N=7
np.vander(x,N)

array([[     1,      1,      1,      1,      1,      1,      1],
       [  4096,   1024,    256,     64,     16,      4,      1],
       [   729,    243,     81,     27,      9,      3,      1],
       [117649,  16807,   2401,    343,     49,      7,      1]])